export const ALTA_PRODUCTO = 'ALTA_PRODUCTO'
export const GESTOR_PRODUCTOS = 'GESTOR_PRODUCTOS'
export const BAJA_PRODUCTOS = 'BAJA_PRODUCTOS'
export const MODIFICACION_PRODUCTOS = 'MODIFICACION_PRODUCTOS'

//USUARIO
export const CERRAR_SESION = 'CERRAR_SESION'