export const ALTA_PRODUCTO = 'ALTA_PRODUCTO'
export const GESTOR_PRODUCTOS = 'GESTOR_PRODUCTOS'
export const BAJA_PRODUCTOS = 'BAJA_PRODUCTOS'
export const MODIFICACION_PRODUCTOS = 'MODIFICACION_PRODUCTOS'
export const CREAR_PRODUCTO = 'CREAR_PRODUCTO'
export const SET_MARCAS = 'SET_MARCAS'
export const SET_RUBROS = 'SET_RUBROS'

//USUARIO
export const CERRAR_SESION = 'CERRAR_SESION'
export const AUTENTICAR_USUARIO = 'AUTENTICAR_USUARIO'

//VENTA
export const MOSTRAR_VENTA = 'MOSTRAR_VENTA'

